---
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /mnt/data/appdata/emby:/config
      - /mnt/data/media/tv:/data/tvshows
      - /mnt/data/media/movies:/data/movies
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      # - 8920:8920 #optional

