---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - VERSION=docker
      - PLEX_CLAIM=claim--v3pb1sn3m_ZsytYif2-
    volumes:
      - ${APPDATA_PATH}/plex:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/anime:/anime
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    labels:
      - "homepage.group=Media"
      - "homepage.name=Plex"
      - "homepage.icon=sh-plex"
      - "homepage.href=http://localhost:32400"
